//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the feature_detector package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __feature_detector__PARAMETERSCONFIG_H__
#define __feature_detector__PARAMETERSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace feature_detector
{
  class ParametersConfigStatics;

  class ParametersConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(ParametersConfig &config, const ParametersConfig &max, const ParametersConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ParametersConfig &config1, const ParametersConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ParametersConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ParametersConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ParametersConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ParametersConfig &config) const = 0;
      virtual void getValue(const ParametersConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T ParametersConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T ParametersConfig::* field;

      virtual void clamp(ParametersConfig &config, const ParametersConfig &max, const ParametersConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ParametersConfig &config1, const ParametersConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ParametersConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ParametersConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ParametersConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ParametersConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ParametersConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ParametersConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, ParametersConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<ParametersConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ParametersConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("match_distance_threshold"==(*_i)->name){match_distance_threshold = boost::any_cast<double>(val);}
        if("ransac_reproj_threshold"==(*_i)->name){ransac_reproj_threshold = boost::any_cast<double>(val);}
        if("object_name"==(*_i)->name){object_name = boost::any_cast<std::string>(val);}
      }
    }

    double match_distance_threshold;
double ransac_reproj_threshold;
std::string object_name;

    bool state;
    std::string name;

    class SURF
{
  public:
    SURF()
    {
      state = true;
      name = "surf";
    }

    void setParams(ParametersConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("hessian_threshold"==(*_i)->name){hessian_threshold = boost::any_cast<double>(val);}
        if("num_octaves"==(*_i)->name){num_octaves = boost::any_cast<int>(val);}
        if("num_octave_layers"==(*_i)->name){num_octave_layers = boost::any_cast<int>(val);}
        if("extended"==(*_i)->name){extended = boost::any_cast<bool>(val);}
        if("upright"==(*_i)->name){upright = boost::any_cast<bool>(val);}
      }
    }

    double hessian_threshold;
int num_octaves;
int num_octave_layers;
bool extended;
bool upright;

    bool state;
    std::string name;

    
}surf;

class MATCHER
{
  public:
    MATCHER()
    {
      state = true;
      name = "matcher";
    }

    void setParams(ParametersConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("norm_type"==(*_i)->name){norm_type = boost::any_cast<int>(val);}
        if("cross_check"==(*_i)->name){cross_check = boost::any_cast<bool>(val);}
      }
    }

    int norm_type;
bool cross_check;

    bool state;
    std::string name;

    
}matcher;

class TARGET_SELECTION
{
  public:
    TARGET_SELECTION()
    {
      state = true;
      name = "target_selection";
    }

    void setParams(ParametersConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("filename"==(*_i)->name){filename = boost::any_cast<std::string>(val);}
        if("save_selection"==(*_i)->name){save_selection = boost::any_cast<bool>(val);}
        if("load_selection"==(*_i)->name){load_selection = boost::any_cast<bool>(val);}
      }
    }

    std::string filename;
bool save_selection;
bool load_selection;

    bool state;
    std::string name;

    
}target_selection;

}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double match_distance_threshold;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double ransac_reproj_threshold;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string object_name;
//#line 12 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      double hessian_threshold;
//#line 15 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      int num_octaves;
//#line 18 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      int num_octave_layers;
//#line 21 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      bool extended;
//#line 24 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      bool upright;
//#line 33 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      int norm_type;
//#line 34 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      bool cross_check;
//#line 38 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      std::string filename;
//#line 40 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      bool save_selection;
//#line 42 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      bool load_selection;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ParametersConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ParametersConfig &__max__ = __getMax__();
      const ParametersConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ParametersConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ParametersConfig &__getDefault__();
    static const ParametersConfig &__getMax__();
    static const ParametersConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const ParametersConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void ParametersConfig::ParamDescription<std::string>::clamp(ParametersConfig &config, const ParametersConfig &max, const ParametersConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class ParametersConfigStatics
  {
    friend class ParametersConfig;

    ParametersConfigStatics()
    {
ParametersConfig::GroupDescription<ParametersConfig::DEFAULT, ParametersConfig> Default("Default", "", 0, 0, true, &ParametersConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.match_distance_threshold = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.match_distance_threshold = 100.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.match_distance_threshold = 0.25;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<double>("match_distance_threshold", "double", 0, "Only matches above this threshold are considered", "", &ParametersConfig::match_distance_threshold)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<double>("match_distance_threshold", "double", 0, "Only matches above this threshold are considered", "", &ParametersConfig::match_distance_threshold)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ransac_reproj_threshold = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ransac_reproj_threshold = 100.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ransac_reproj_threshold = 3.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<double>("ransac_reproj_threshold", "double", 0, "Only points with a smaller reprojection-error are considered when finding the homography", "", &ParametersConfig::ransac_reproj_threshold)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<double>("ransac_reproj_threshold", "double", 0, "Only points with a smaller reprojection-error are considered when finding the homography", "", &ParametersConfig::ransac_reproj_threshold)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.object_name = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.object_name = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.object_name = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<std::string>("object_name", "str", 0, "Name that is given to detected objects", "", &ParametersConfig::object_name)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<std::string>("object_name", "str", 0, "Name that is given to detected objects", "", &ParametersConfig::object_name)));
ParametersConfig::GroupDescription<ParametersConfig::DEFAULT::SURF, ParametersConfig::DEFAULT> surf("surf", "", 0, 1, true, &ParametersConfig::DEFAULT::surf);
//#line 12 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __min__.hessian_threshold = 2.0;
//#line 12 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __max__.hessian_threshold = 10000.0;
//#line 12 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __default__.hessian_threshold = 500.0;
//#line 12 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      surf.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<double>("hessian_threshold", "double", 0, "Only local extrema with a Hessian-determinant above this will be kept as keypoints", "", &ParametersConfig::hessian_threshold)));
//#line 12 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<double>("hessian_threshold", "double", 0, "Only local extrema with a Hessian-determinant above this will be kept as keypoints", "", &ParametersConfig::hessian_threshold)));
//#line 15 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __min__.num_octaves = 1;
//#line 15 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __max__.num_octaves = 20;
//#line 15 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __default__.num_octaves = 4;
//#line 15 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      surf.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<int>("num_octaves", "int", 0, "Number of pyramid octaves", "", &ParametersConfig::num_octaves)));
//#line 15 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<int>("num_octaves", "int", 0, "Number of pyramid octaves", "", &ParametersConfig::num_octaves)));
//#line 18 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __min__.num_octave_layers = 1;
//#line 18 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __max__.num_octave_layers = 20;
//#line 18 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __default__.num_octave_layers = 3;
//#line 18 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      surf.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<int>("num_octave_layers", "int", 0, "Number of images in each octave", "", &ParametersConfig::num_octave_layers)));
//#line 18 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<int>("num_octave_layers", "int", 0, "Number of images in each octave", "", &ParametersConfig::num_octave_layers)));
//#line 21 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __min__.extended = 0;
//#line 21 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __max__.extended = 1;
//#line 21 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __default__.extended = 0;
//#line 21 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      surf.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<bool>("extended", "bool", 0, "false: 64-element; true: 128-element descriptor", "", &ParametersConfig::extended)));
//#line 21 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<bool>("extended", "bool", 0, "false: 64-element; true: 128-element descriptor", "", &ParametersConfig::extended)));
//#line 24 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __min__.upright = 0;
//#line 24 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __max__.upright = 1;
//#line 24 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __default__.upright = 0;
//#line 24 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      surf.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<bool>("upright", "bool", 0, "true: don't compute orientation", "", &ParametersConfig::upright)));
//#line 24 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<bool>("upright", "bool", 0, "true: don't compute orientation", "", &ParametersConfig::upright)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      surf.convertParams();
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(ParametersConfig::AbstractGroupDescriptionConstPtr(new ParametersConfig::GroupDescription<ParametersConfig::DEFAULT::SURF, ParametersConfig::DEFAULT>(surf)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ParametersConfig::AbstractGroupDescriptionConstPtr(new ParametersConfig::GroupDescription<ParametersConfig::DEFAULT::SURF, ParametersConfig::DEFAULT>(surf)));
ParametersConfig::GroupDescription<ParametersConfig::DEFAULT::MATCHER, ParametersConfig::DEFAULT> matcher("matcher", "", 0, 2, true, &ParametersConfig::DEFAULT::matcher);
//#line 33 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __min__.norm_type = 2;
//#line 33 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __max__.norm_type = 4;
//#line 33 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __default__.norm_type = 4;
//#line 33 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      matcher.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<int>("norm_type", "int", 0, "Type for calculating norms", "{'enum_description': 'An enum to set the norm-type, used by the matcher', 'enum': [{'srcline': 28, 'description': 'Sum of absolute differences', 'srcfile': '/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'L1'}, {'srcline': 29, 'description': 'Sqrt of sum of squared differences', 'srcfile': '/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg', 'cconsttype': 'const int', 'value': 4, 'ctype': 'int', 'type': 'int', 'name': 'L2'}]}", &ParametersConfig::norm_type)));
//#line 33 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<int>("norm_type", "int", 0, "Type for calculating norms", "{'enum_description': 'An enum to set the norm-type, used by the matcher', 'enum': [{'srcline': 28, 'description': 'Sum of absolute differences', 'srcfile': '/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'L1'}, {'srcline': 29, 'description': 'Sqrt of sum of squared differences', 'srcfile': '/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg', 'cconsttype': 'const int', 'value': 4, 'ctype': 'int', 'type': 'int', 'name': 'L2'}]}", &ParametersConfig::norm_type)));
//#line 34 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __min__.cross_check = 0;
//#line 34 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __max__.cross_check = 1;
//#line 34 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __default__.cross_check = 0;
//#line 34 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      matcher.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<bool>("cross_check", "bool", 0, "Cross-checking", "", &ParametersConfig::cross_check)));
//#line 34 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<bool>("cross_check", "bool", 0, "Cross-checking", "", &ParametersConfig::cross_check)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      matcher.convertParams();
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(ParametersConfig::AbstractGroupDescriptionConstPtr(new ParametersConfig::GroupDescription<ParametersConfig::DEFAULT::MATCHER, ParametersConfig::DEFAULT>(matcher)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ParametersConfig::AbstractGroupDescriptionConstPtr(new ParametersConfig::GroupDescription<ParametersConfig::DEFAULT::MATCHER, ParametersConfig::DEFAULT>(matcher)));
ParametersConfig::GroupDescription<ParametersConfig::DEFAULT::TARGET_SELECTION, ParametersConfig::DEFAULT> target_selection("target_selection", "", 0, 3, true, &ParametersConfig::DEFAULT::target_selection);
//#line 38 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __min__.filename = "";
//#line 38 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __max__.filename = "";
//#line 38 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __default__.filename = "";
//#line 38 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      target_selection.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<std::string>("filename", "str", 0, "Name of file for saving/loading target selection", "", &ParametersConfig::filename)));
//#line 38 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<std::string>("filename", "str", 0, "Name of file for saving/loading target selection", "", &ParametersConfig::filename)));
//#line 40 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __min__.save_selection = 0;
//#line 40 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __max__.save_selection = 1;
//#line 40 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __default__.save_selection = 0;
//#line 40 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      target_selection.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<bool>("save_selection", "bool", 0, "Save current area/target selection to file", "", &ParametersConfig::save_selection)));
//#line 40 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<bool>("save_selection", "bool", 0, "Save current area/target selection to file", "", &ParametersConfig::save_selection)));
//#line 42 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __min__.load_selection = 0;
//#line 42 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __max__.load_selection = 1;
//#line 42 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __default__.load_selection = 0;
//#line 42 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      target_selection.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<bool>("load_selection", "bool", 0, "Load area/target selection from file", "", &ParametersConfig::load_selection)));
//#line 42 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<bool>("load_selection", "bool", 0, "Load area/target selection from file", "", &ParametersConfig::load_selection)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      target_selection.convertParams();
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(ParametersConfig::AbstractGroupDescriptionConstPtr(new ParametersConfig::GroupDescription<ParametersConfig::DEFAULT::TARGET_SELECTION, ParametersConfig::DEFAULT>(target_selection)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ParametersConfig::AbstractGroupDescriptionConstPtr(new ParametersConfig::GroupDescription<ParametersConfig::DEFAULT::TARGET_SELECTION, ParametersConfig::DEFAULT>(target_selection)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ParametersConfig::AbstractGroupDescriptionConstPtr(new ParametersConfig::GroupDescription<ParametersConfig::DEFAULT, ParametersConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<ParametersConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<ParametersConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ParametersConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ParametersConfig __max__;
    ParametersConfig __min__;
    ParametersConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ParametersConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ParametersConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ParametersConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const ParametersConfig &ParametersConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const ParametersConfig &ParametersConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const ParametersConfig &ParametersConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<ParametersConfig::AbstractParamDescriptionConstPtr> &ParametersConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ParametersConfig::AbstractGroupDescriptionConstPtr> &ParametersConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ParametersConfigStatics *ParametersConfig::__get_statics__()
  {
    const static ParametersConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ParametersConfigStatics::get_instance();

    return statics;
  }

//#line 28 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      const int Parameters_L1 = 2;
//#line 29 "/home/bit/catkin_ws/src/ros_object_recognition/src/feature_detector/cfg/Parameters.cfg"
      const int Parameters_L2 = 4;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __PARAMETERSRECONFIGURATOR_H__
