// Generated by gencpp from file object_detection_3d_msgs/DetectedObject3DArray.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECTION_3D_MSGS_MESSAGE_DETECTEDOBJECT3DARRAY_H
#define OBJECT_DETECTION_3D_MSGS_MESSAGE_DETECTEDOBJECT3DARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <object_detection_3d_msgs/DetectedObject3D.h>

namespace object_detection_3d_msgs
{
template <class ContainerAllocator>
struct DetectedObject3DArray_
{
  typedef DetectedObject3DArray_<ContainerAllocator> Type;

  DetectedObject3DArray_()
    : header()
    , objects()  {
    }
  DetectedObject3DArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::object_detection_3d_msgs::DetectedObject3D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::object_detection_3d_msgs::DetectedObject3D_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator> const> ConstPtr;

}; // struct DetectedObject3DArray_

typedef ::object_detection_3d_msgs::DetectedObject3DArray_<std::allocator<void> > DetectedObject3DArray;

typedef boost::shared_ptr< ::object_detection_3d_msgs::DetectedObject3DArray > DetectedObject3DArrayPtr;
typedef boost::shared_ptr< ::object_detection_3d_msgs::DetectedObject3DArray const> DetectedObject3DArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator1> & lhs, const ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator1> & lhs, const ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_detection_3d_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80c68494d0ddf60329a33fe213c4031f";
  }

  static const char* value(const ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80c68494d0ddf603ULL;
  static const uint64_t static_value2 = 0x29a33fe213c4031fULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_detection_3d_msgs/DetectedObject3DArray";
  }

  static const char* value(const ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"DetectedObject3D[] objects\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: object_detection_3d_msgs/DetectedObject3D\n"
"string name\n"
"OrientedBox box\n"
"\n"
"================================================================================\n"
"MSG: object_detection_3d_msgs/OrientedBox\n"
"# Pose = position of centroid of object + orientation of object.\n"
"geometry_msgs/Pose pose\n"
"\n"
"# Dimensions of the box.\n"
"float64 width\n"
"float64 height\n"
"float64 depth\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectedObject3DArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_detection_3d_msgs::DetectedObject3DArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::object_detection_3d_msgs::DetectedObject3D_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECTION_3D_MSGS_MESSAGE_DETECTEDOBJECT3DARRAY_H
