# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from object_detection_3d_msgs/DetectedObject3D.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import object_detection_3d_msgs.msg

class DetectedObject3D(genpy.Message):
  _md5sum = "313c73372cba8ca3b40d40c0f7d90ff3"
  _type = "object_detection_3d_msgs/DetectedObject3D"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string name
OrientedBox box

================================================================================
MSG: object_detection_3d_msgs/OrientedBox
# Pose = position of centroid of object + orientation of object.
geometry_msgs/Pose pose

# Dimensions of the box.
float64 width
float64 height
float64 depth

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['name','box']
  _slot_types = ['string','object_detection_3d_msgs/OrientedBox']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       name,box

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DetectedObject3D, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.name is None:
        self.name = ''
      if self.box is None:
        self.box = object_detection_3d_msgs.msg.OrientedBox()
    else:
      self.name = ''
      self.box = object_detection_3d_msgs.msg.OrientedBox()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_10d().pack(_x.box.pose.position.x, _x.box.pose.position.y, _x.box.pose.position.z, _x.box.pose.orientation.x, _x.box.pose.orientation.y, _x.box.pose.orientation.z, _x.box.pose.orientation.w, _x.box.width, _x.box.height, _x.box.depth))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.box is None:
        self.box = object_detection_3d_msgs.msg.OrientedBox()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.box.pose.position.x, _x.box.pose.position.y, _x.box.pose.position.z, _x.box.pose.orientation.x, _x.box.pose.orientation.y, _x.box.pose.orientation.z, _x.box.pose.orientation.w, _x.box.width, _x.box.height, _x.box.depth,) = _get_struct_10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_10d().pack(_x.box.pose.position.x, _x.box.pose.position.y, _x.box.pose.position.z, _x.box.pose.orientation.x, _x.box.pose.orientation.y, _x.box.pose.orientation.z, _x.box.pose.orientation.w, _x.box.width, _x.box.height, _x.box.depth))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.box is None:
        self.box = object_detection_3d_msgs.msg.OrientedBox()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.box.pose.position.x, _x.box.pose.position.y, _x.box.pose.position.z, _x.box.pose.orientation.x, _x.box.pose.orientation.y, _x.box.pose.orientation.z, _x.box.pose.orientation.w, _x.box.width, _x.box.height, _x.box.depth,) = _get_struct_10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10d = None
def _get_struct_10d():
    global _struct_10d
    if _struct_10d is None:
        _struct_10d = struct.Struct("<10d")
    return _struct_10d
