// Generated by gencpp from file object_detection_2d_msgs/DetectedObject2DArray.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECTION_2D_MSGS_MESSAGE_DETECTEDOBJECT2DARRAY_H
#define OBJECT_DETECTION_2D_MSGS_MESSAGE_DETECTEDOBJECT2DARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <object_detection_2d_msgs/DetectedObject2D.h>

namespace object_detection_2d_msgs
{
template <class ContainerAllocator>
struct DetectedObject2DArray_
{
  typedef DetectedObject2DArray_<ContainerAllocator> Type;

  DetectedObject2DArray_()
    : header()
    , objects()  {
    }
  DetectedObject2DArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::object_detection_2d_msgs::DetectedObject2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::object_detection_2d_msgs::DetectedObject2D_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator> const> ConstPtr;

}; // struct DetectedObject2DArray_

typedef ::object_detection_2d_msgs::DetectedObject2DArray_<std::allocator<void> > DetectedObject2DArray;

typedef boost::shared_ptr< ::object_detection_2d_msgs::DetectedObject2DArray > DetectedObject2DArrayPtr;
typedef boost::shared_ptr< ::object_detection_2d_msgs::DetectedObject2DArray const> DetectedObject2DArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator1> & lhs, const ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator1> & lhs, const ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_detection_2d_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f000d144a2435e976874e58da56b6a7";
  }

  static const char* value(const ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f000d144a2435e9ULL;
  static const uint64_t static_value2 = 0x76874e58da56b6a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_detection_2d_msgs/DetectedObject2DArray";
  }

  static const char* value(const ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"DetectedObject2D[] objects\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: object_detection_2d_msgs/DetectedObject2D\n"
"string name\n"
"\n"
"# We use a polygon to represent the location of the object in pixel space.\n"
"# This gives us a very general description of the object and many possibilities\n"
"# for describing the contour of the object.\n"
"# Polygon is also predefined in the geometry_msgs package. We set the\n"
"# z-coordinate of the points in the polygon to zero since we work in pixel\n"
"# space.\n"
"geometry_msgs/Polygon polygon\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectedObject2DArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_detection_2d_msgs::DetectedObject2DArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::object_detection_2d_msgs::DetectedObject2D_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECTION_2D_MSGS_MESSAGE_DETECTEDOBJECT2DARRAY_H
