//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the shape_detector package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __shape_detector__PARAMETERSCONFIG_H__
#define __shape_detector__PARAMETERSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace shape_detector
{
  class ParametersConfigStatics;

  class ParametersConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(ParametersConfig &config, const ParametersConfig &max, const ParametersConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ParametersConfig &config1, const ParametersConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ParametersConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ParametersConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ParametersConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ParametersConfig &config) const = 0;
      virtual void getValue(const ParametersConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T ParametersConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T ParametersConfig::* field;

      virtual void clamp(ParametersConfig &config, const ParametersConfig &max, const ParametersConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ParametersConfig &config1, const ParametersConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ParametersConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ParametersConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ParametersConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ParametersConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ParametersConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ParametersConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, ParametersConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<ParametersConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ParametersConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("object_name"==(*_i)->name){object_name = boost::any_cast<std::string>(val);}
        if("shape"==(*_i)->name){shape = boost::any_cast<int>(val);}
        if("normal_distance_weight"==(*_i)->name){normal_distance_weight = boost::any_cast<double>(val);}
        if("distance_threshold"==(*_i)->name){distance_threshold = boost::any_cast<double>(val);}
        if("num_nearest_neighbors"==(*_i)->name){num_nearest_neighbors = boost::any_cast<int>(val);}
        if("max_iterations"==(*_i)->name){max_iterations = boost::any_cast<int>(val);}
        if("optimize_coefficients"==(*_i)->name){optimize_coefficients = boost::any_cast<bool>(val);}
      }
    }

    std::string object_name;
int shape;
double normal_distance_weight;
double distance_threshold;
int num_nearest_neighbors;
int max_iterations;
bool optimize_coefficients;

    bool state;
    std::string name;

    class RADII
{
  public:
    RADII()
    {
      state = true;
      name = "Radii";
    }

    void setParams(ParametersConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("min_radius"==(*_i)->name){min_radius = boost::any_cast<double>(val);}
        if("max_radius"==(*_i)->name){max_radius = boost::any_cast<double>(val);}
      }
    }

    double min_radius;
double max_radius;

    bool state;
    std::string name;

    
}radii;

}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string object_name;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int shape;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double normal_distance_weight;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double distance_threshold;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int num_nearest_neighbors;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int max_iterations;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool optimize_coefficients;
//#line 26 "/home/bit/catkin_ws/src/ros_object_recognition/src/shape_detector/cfg/Parameters.cfg"
      double min_radius;
//#line 29 "/home/bit/catkin_ws/src/ros_object_recognition/src/shape_detector/cfg/Parameters.cfg"
      double max_radius;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ParametersConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ParametersConfig &__max__ = __getMax__();
      const ParametersConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ParametersConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ParametersConfig &__getDefault__();
    static const ParametersConfig &__getMax__();
    static const ParametersConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const ParametersConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void ParametersConfig::ParamDescription<std::string>::clamp(ParametersConfig &config, const ParametersConfig &max, const ParametersConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class ParametersConfigStatics
  {
    friend class ParametersConfig;

    ParametersConfigStatics()
    {
ParametersConfig::GroupDescription<ParametersConfig::DEFAULT, ParametersConfig> Default("Default", "", 0, 0, true, &ParametersConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.object_name = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.object_name = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.object_name = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<std::string>("object_name", "str", 0, "Name that is given to detected objects", "", &ParametersConfig::object_name)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<std::string>("object_name", "str", 0, "Name that is given to detected objects", "", &ParametersConfig::object_name)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.shape = 4;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.shape = 5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.shape = 5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<int>("shape", "int", 0, "Shape that we try to detect", "{'enum_description': 'An enum to set the shape', 'enum': [{'srcline': 13, 'description': 'Detect a cylinder', 'srcfile': '/home/bit/catkin_ws/src/ros_object_recognition/src/shape_detector/cfg/Parameters.cfg', 'cconsttype': 'const int', 'value': 5, 'ctype': 'int', 'type': 'int', 'name': 'Cylinder'}, {'srcline': 14, 'description': 'Detect a sphere', 'srcfile': '/home/bit/catkin_ws/src/ros_object_recognition/src/shape_detector/cfg/Parameters.cfg', 'cconsttype': 'const int', 'value': 4, 'ctype': 'int', 'type': 'int', 'name': 'Sphere'}]}", &ParametersConfig::shape)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<int>("shape", "int", 0, "Shape that we try to detect", "{'enum_description': 'An enum to set the shape', 'enum': [{'srcline': 13, 'description': 'Detect a cylinder', 'srcfile': '/home/bit/catkin_ws/src/ros_object_recognition/src/shape_detector/cfg/Parameters.cfg', 'cconsttype': 'const int', 'value': 5, 'ctype': 'int', 'type': 'int', 'name': 'Cylinder'}, {'srcline': 14, 'description': 'Detect a sphere', 'srcfile': '/home/bit/catkin_ws/src/ros_object_recognition/src/shape_detector/cfg/Parameters.cfg', 'cconsttype': 'const int', 'value': 4, 'ctype': 'int', 'type': 'int', 'name': 'Sphere'}]}", &ParametersConfig::shape)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.normal_distance_weight = 0.001;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.normal_distance_weight = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.normal_distance_weight = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<double>("normal_distance_weight", "double", 0, "normal-distance-weight", "", &ParametersConfig::normal_distance_weight)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<double>("normal_distance_weight", "double", 0, "normal-distance-weight", "", &ParametersConfig::normal_distance_weight)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.distance_threshold = 0.001;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.distance_threshold = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.distance_threshold = 0.05;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<double>("distance_threshold", "double", 0, "distance-threshold", "", &ParametersConfig::distance_threshold)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<double>("distance_threshold", "double", 0, "distance-threshold", "", &ParametersConfig::distance_threshold)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.num_nearest_neighbors = 5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.num_nearest_neighbors = 100;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.num_nearest_neighbors = 50;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<int>("num_nearest_neighbors", "int", 0, "Number nearest neighbors used to calculate normals", "", &ParametersConfig::num_nearest_neighbors)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<int>("num_nearest_neighbors", "int", 0, "Number nearest neighbors used to calculate normals", "", &ParametersConfig::num_nearest_neighbors)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_iterations = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_iterations = 20000;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_iterations = 100;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<int>("max_iterations", "int", 0, "Maximum number of iterations", "", &ParametersConfig::max_iterations)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<int>("max_iterations", "int", 0, "Maximum number of iterations", "", &ParametersConfig::max_iterations)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.optimize_coefficients = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.optimize_coefficients = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.optimize_coefficients = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<bool>("optimize_coefficients", "bool", 0, "Optimize coefficients", "", &ParametersConfig::optimize_coefficients)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<bool>("optimize_coefficients", "bool", 0, "Optimize coefficients", "", &ParametersConfig::optimize_coefficients)));
ParametersConfig::GroupDescription<ParametersConfig::DEFAULT::RADII, ParametersConfig::DEFAULT> Radii("Radii", "", 0, 1, true, &ParametersConfig::DEFAULT::radii);
//#line 26 "/home/bit/catkin_ws/src/ros_object_recognition/src/shape_detector/cfg/Parameters.cfg"
      __min__.min_radius = 0.01;
//#line 26 "/home/bit/catkin_ws/src/ros_object_recognition/src/shape_detector/cfg/Parameters.cfg"
      __max__.min_radius = 1.0;
//#line 26 "/home/bit/catkin_ws/src/ros_object_recognition/src/shape_detector/cfg/Parameters.cfg"
      __default__.min_radius = 0.1;
//#line 26 "/home/bit/catkin_ws/src/ros_object_recognition/src/shape_detector/cfg/Parameters.cfg"
      Radii.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<double>("min_radius", "double", 0, "Objects with a smaller radius will not be detected", "", &ParametersConfig::min_radius)));
//#line 26 "/home/bit/catkin_ws/src/ros_object_recognition/src/shape_detector/cfg/Parameters.cfg"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<double>("min_radius", "double", 0, "Objects with a smaller radius will not be detected", "", &ParametersConfig::min_radius)));
//#line 29 "/home/bit/catkin_ws/src/ros_object_recognition/src/shape_detector/cfg/Parameters.cfg"
      __min__.max_radius = 0.01;
//#line 29 "/home/bit/catkin_ws/src/ros_object_recognition/src/shape_detector/cfg/Parameters.cfg"
      __max__.max_radius = 1.0;
//#line 29 "/home/bit/catkin_ws/src/ros_object_recognition/src/shape_detector/cfg/Parameters.cfg"
      __default__.max_radius = 0.2;
//#line 29 "/home/bit/catkin_ws/src/ros_object_recognition/src/shape_detector/cfg/Parameters.cfg"
      Radii.abstract_parameters.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<double>("max_radius", "double", 0, "Objects with a greater radius will not be detected", "", &ParametersConfig::max_radius)));
//#line 29 "/home/bit/catkin_ws/src/ros_object_recognition/src/shape_detector/cfg/Parameters.cfg"
      __param_descriptions__.push_back(ParametersConfig::AbstractParamDescriptionConstPtr(new ParametersConfig::ParamDescription<double>("max_radius", "double", 0, "Objects with a greater radius will not be detected", "", &ParametersConfig::max_radius)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Radii.convertParams();
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(ParametersConfig::AbstractGroupDescriptionConstPtr(new ParametersConfig::GroupDescription<ParametersConfig::DEFAULT::RADII, ParametersConfig::DEFAULT>(Radii)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ParametersConfig::AbstractGroupDescriptionConstPtr(new ParametersConfig::GroupDescription<ParametersConfig::DEFAULT::RADII, ParametersConfig::DEFAULT>(Radii)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ParametersConfig::AbstractGroupDescriptionConstPtr(new ParametersConfig::GroupDescription<ParametersConfig::DEFAULT, ParametersConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<ParametersConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<ParametersConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ParametersConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ParametersConfig __max__;
    ParametersConfig __min__;
    ParametersConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ParametersConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ParametersConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ParametersConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const ParametersConfig &ParametersConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const ParametersConfig &ParametersConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const ParametersConfig &ParametersConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<ParametersConfig::AbstractParamDescriptionConstPtr> &ParametersConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ParametersConfig::AbstractGroupDescriptionConstPtr> &ParametersConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ParametersConfigStatics *ParametersConfig::__get_statics__()
  {
    const static ParametersConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ParametersConfigStatics::get_instance();

    return statics;
  }

//#line 13 "/home/bit/catkin_ws/src/ros_object_recognition/src/shape_detector/cfg/Parameters.cfg"
      const int Parameters_Cylinder = 5;
//#line 14 "/home/bit/catkin_ws/src/ros_object_recognition/src/shape_detector/cfg/Parameters.cfg"
      const int Parameters_Sphere = 4;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __PARAMETERSRECONFIGURATOR_H__
